// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter/collector (interfaces: Collector)
//
// Generated by this command:
//
//	mockgen -destination=mocks/pkg/dcgmexporter/collector/mock_expcollector.go github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter/collector Collector
//

// Package mock_collector is a generated GoMock package.
package mock_collector

import (
	reflect "reflect"

	collector "github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter/collector"
	sysinfo "github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter/sysinfo"
	gomock "go.uber.org/mock/gomock"
)

// MockCollector is a mock of Collector interface.
type MockCollector struct {
	ctrl     *gomock.Controller
	recorder *MockCollectorMockRecorder
}

// MockCollectorMockRecorder is the mock recorder for MockCollector.
type MockCollectorMockRecorder struct {
	mock *MockCollector
}

// NewMockCollector creates a new mock instance.
func NewMockCollector(ctrl *gomock.Controller) *MockCollector {
	mock := &MockCollector{ctrl: ctrl}
	mock.recorder = &MockCollectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCollector) EXPECT() *MockCollectorMockRecorder {
	return m.recorder
}

// Cleanup mocks base method.
func (m *MockCollector) Cleanup() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Cleanup")
}

// Cleanup indicates an expected call of Cleanup.
func (mr *MockCollectorMockRecorder) Cleanup() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleanup", reflect.TypeOf((*MockCollector)(nil).Cleanup))
}

// GetMetrics mocks base method.
func (m *MockCollector) GetMetrics() (collector.MetricsByCounter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetrics")
	ret0, _ := ret[0].(collector.MetricsByCounter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetrics indicates an expected call of GetMetrics.
func (mr *MockCollectorMockRecorder) GetMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetrics", reflect.TypeOf((*MockCollector)(nil).GetMetrics))
}

// GetSysinfo mocks base method.
func (m *MockCollector) GetSysinfo() sysinfo.SystemInfoInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSysinfo")
	ret0, _ := ret[0].(sysinfo.SystemInfoInterface)
	return ret0
}

// GetSysinfo indicates an expected call of GetSysinfo.
func (mr *MockCollectorMockRecorder) GetSysinfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSysinfo", reflect.TypeOf((*MockCollector)(nil).GetSysinfo))
}
