linters:
  enable:
    - contextcheck
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - gofumpt

linters-settings:
  goimports:
    local-prefixes: github.com/NVIDIA/dcgm-exporter

