# Copyright (c) 2021, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "dcgm-exporter"
  labels:
    app.kubernetes.io/name: "dcgm-exporter"
    app.kubernetes.io/version: "4.1.1"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "dcgm-exporter"
      app.kubernetes.io/version: "4.1.1"
  endpoints:
  - port: "metrics"
    path: "/metrics"
    metricRelabelings:
    - action: replace
      regex: DCGM_FI_DEV_GPU_UTIL
      replacement: accelerator_gpu_utilization
      sourceLabels:
      - __name__
      targetLabel: __name__
    - action: replace
      regex: DCGM_FI_DEV_MEM_COPY_UTIL
      replacement: accelerator_memory_used_bytes
      sourceLabels:
      - __name__
      targetLabel: __name__
    - action: replace
      regex: DCGM_FI_DEV_FB_TOTAL
      replacement: accelerator_memory_total_bytes
      sourceLabels:
      - __name__
      targetLabel: __name__
    - action: replace
      regex: DCGM_FI_DEV_POWER_USAGE
      replacement: accelerator_power_usage_watts
      sourceLabels:
      - __name__
      targetLabel: __name__
    - action: replace
      regex: DCGM_FI_DEV_GPU_TEMP
      replacement: accelerator_temperature_celcius
      sourceLabels:
      - __name__
      targetLabel: __name__
    - action: replace
      regex: DCGM_FI_DEV_SM_CLOCK
      replacement: accelerator_sm_clock_hertz
      sourceLabels:
      - __name__
      targetLabel: __name__
    - action: replace
      regex: DCGM_FI_DEV_MEM_CLOCK
      replacement: accelerator_memory_cloc_hertz
      sourceLabels:
      - __name__
      targetLabel: __name__
    relabelings:
    - action: replace
      replacement: nvidia
      targetLabel: vendor_id
