{{- if or (and (or .Values.kubernetes.enablePodLabels .Values.kubernetes.enablePodUID) .Values.kubernetes.rbac.create) .Values.kubernetesDRA.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dcgm-exporter.fullname" . }}-read-pods
  labels:
    {{- include "dcgm-exporter.labels" . | nindent 4 }}
rules:
- apiGroups: ["", "resource.k8s.io"]
  resources: ["pods", "resourceslices"]
  verbs: ["get", "list", "watch"]
{{- end }}
