// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter/dcgmprovider (interfaces: DCGMProvider)
//
// Generated by this command:
//
//	mockgen -destination=mocks/pkg/dcgmexporter/dcgmprovider/mock_client.go github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter/dcgmprovider DCGMProvider
//

// Package mock_dcgmprovider is a generated GoMock package.
package mock_dcgmprovider

import (
	reflect "reflect"
	time "time"

	dcgm "github.com/NVIDIA/go-dcgm/pkg/dcgm"
	gomock "go.uber.org/mock/gomock"
)

// MockDCGMProvider is a mock of DCGMProvider interface.
type MockDCGMProvider struct {
	ctrl     *gomock.Controller
	recorder *MockDCGMProviderMockRecorder
}

// MockDCGMProviderMockRecorder is the mock recorder for MockDCGMProvider.
type MockDCGMProviderMockRecorder struct {
	mock *MockDCGMProvider
}

// NewMockDCGMProvider creates a new mock instance.
func NewMockDCGMProvider(ctrl *gomock.Controller) *MockDCGMProvider {
	mock := &MockDCGMProvider{ctrl: ctrl}
	mock.recorder = &MockDCGMProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDCGMProvider) EXPECT() *MockDCGMProviderMockRecorder {
	return m.recorder
}

// AddEntityToGroup mocks base method.
func (m *MockDCGMProvider) AddEntityToGroup(arg0 dcgm.GroupHandle, arg1 dcgm.Field_Entity_Group, arg2 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEntityToGroup", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddEntityToGroup indicates an expected call of AddEntityToGroup.
func (mr *MockDCGMProviderMockRecorder) AddEntityToGroup(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEntityToGroup", reflect.TypeOf((*MockDCGMProvider)(nil).AddEntityToGroup), arg0, arg1, arg2)
}

// AddLinkEntityToGroup mocks base method.
func (m *MockDCGMProvider) AddLinkEntityToGroup(arg0 dcgm.GroupHandle, arg1, arg2 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLinkEntityToGroup", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddLinkEntityToGroup indicates an expected call of AddLinkEntityToGroup.
func (mr *MockDCGMProviderMockRecorder) AddLinkEntityToGroup(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLinkEntityToGroup", reflect.TypeOf((*MockDCGMProvider)(nil).AddLinkEntityToGroup), arg0, arg1, arg2)
}

// Cleanup mocks base method.
func (m *MockDCGMProvider) Cleanup() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Cleanup")
}

// Cleanup indicates an expected call of Cleanup.
func (mr *MockDCGMProviderMockRecorder) Cleanup() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleanup", reflect.TypeOf((*MockDCGMProvider)(nil).Cleanup))
}

// CreateGroup mocks base method.
func (m *MockDCGMProvider) CreateGroup(arg0 string) (dcgm.GroupHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroup", arg0)
	ret0, _ := ret[0].(dcgm.GroupHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGroup indicates an expected call of CreateGroup.
func (mr *MockDCGMProviderMockRecorder) CreateGroup(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroup", reflect.TypeOf((*MockDCGMProvider)(nil).CreateGroup), arg0)
}

// DestroyGroup mocks base method.
func (m *MockDCGMProvider) DestroyGroup(arg0 dcgm.GroupHandle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroyGroup", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroyGroup indicates an expected call of DestroyGroup.
func (mr *MockDCGMProviderMockRecorder) DestroyGroup(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyGroup", reflect.TypeOf((*MockDCGMProvider)(nil).DestroyGroup), arg0)
}

// EntitiesGetLatestValues mocks base method.
func (m *MockDCGMProvider) EntitiesGetLatestValues(arg0 []dcgm.GroupEntityPair, arg1 []dcgm.Short, arg2 uint) ([]dcgm.FieldValue_v2, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EntitiesGetLatestValues", arg0, arg1, arg2)
	ret0, _ := ret[0].([]dcgm.FieldValue_v2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EntitiesGetLatestValues indicates an expected call of EntitiesGetLatestValues.
func (mr *MockDCGMProviderMockRecorder) EntitiesGetLatestValues(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EntitiesGetLatestValues", reflect.TypeOf((*MockDCGMProvider)(nil).EntitiesGetLatestValues), arg0, arg1, arg2)
}

// EntityGetLatestValues mocks base method.
func (m *MockDCGMProvider) EntityGetLatestValues(arg0 dcgm.Field_Entity_Group, arg1 uint, arg2 []dcgm.Short) ([]dcgm.FieldValue_v1, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EntityGetLatestValues", arg0, arg1, arg2)
	ret0, _ := ret[0].([]dcgm.FieldValue_v1)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EntityGetLatestValues indicates an expected call of EntityGetLatestValues.
func (mr *MockDCGMProviderMockRecorder) EntityGetLatestValues(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EntityGetLatestValues", reflect.TypeOf((*MockDCGMProvider)(nil).EntityGetLatestValues), arg0, arg1, arg2)
}

// FieldGetById mocks base method.
func (m *MockDCGMProvider) FieldGetById(arg0 dcgm.Short) dcgm.FieldMeta {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FieldGetById", arg0)
	ret0, _ := ret[0].(dcgm.FieldMeta)
	return ret0
}

// FieldGetById indicates an expected call of FieldGetById.
func (mr *MockDCGMProviderMockRecorder) FieldGetById(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FieldGetById", reflect.TypeOf((*MockDCGMProvider)(nil).FieldGetById), arg0)
}

// FieldGroupCreate mocks base method.
func (m *MockDCGMProvider) FieldGroupCreate(arg0 string, arg1 []dcgm.Short) (dcgm.FieldHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FieldGroupCreate", arg0, arg1)
	ret0, _ := ret[0].(dcgm.FieldHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FieldGroupCreate indicates an expected call of FieldGroupCreate.
func (mr *MockDCGMProviderMockRecorder) FieldGroupCreate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FieldGroupCreate", reflect.TypeOf((*MockDCGMProvider)(nil).FieldGroupCreate), arg0, arg1)
}

// FieldGroupDestroy mocks base method.
func (m *MockDCGMProvider) FieldGroupDestroy(arg0 dcgm.FieldHandle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FieldGroupDestroy", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// FieldGroupDestroy indicates an expected call of FieldGroupDestroy.
func (mr *MockDCGMProviderMockRecorder) FieldGroupDestroy(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FieldGroupDestroy", reflect.TypeOf((*MockDCGMProvider)(nil).FieldGroupDestroy), arg0)
}

// GetAllDeviceCount mocks base method.
func (m *MockDCGMProvider) GetAllDeviceCount() (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllDeviceCount")
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllDeviceCount indicates an expected call of GetAllDeviceCount.
func (mr *MockDCGMProviderMockRecorder) GetAllDeviceCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllDeviceCount", reflect.TypeOf((*MockDCGMProvider)(nil).GetAllDeviceCount))
}

// GetCpuHierarchy mocks base method.
func (m *MockDCGMProvider) GetCpuHierarchy() (dcgm.CpuHierarchy_v1, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCpuHierarchy")
	ret0, _ := ret[0].(dcgm.CpuHierarchy_v1)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCpuHierarchy indicates an expected call of GetCpuHierarchy.
func (mr *MockDCGMProviderMockRecorder) GetCpuHierarchy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCpuHierarchy", reflect.TypeOf((*MockDCGMProvider)(nil).GetCpuHierarchy))
}

// GetDeviceInfo mocks base method.
func (m *MockDCGMProvider) GetDeviceInfo(arg0 uint) (dcgm.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceInfo", arg0)
	ret0, _ := ret[0].(dcgm.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceInfo indicates an expected call of GetDeviceInfo.
func (mr *MockDCGMProviderMockRecorder) GetDeviceInfo(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceInfo", reflect.TypeOf((*MockDCGMProvider)(nil).GetDeviceInfo), arg0)
}

// GetEntityGroupEntities mocks base method.
func (m *MockDCGMProvider) GetEntityGroupEntities(arg0 dcgm.Field_Entity_Group) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntityGroupEntities", arg0)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntityGroupEntities indicates an expected call of GetEntityGroupEntities.
func (mr *MockDCGMProviderMockRecorder) GetEntityGroupEntities(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntityGroupEntities", reflect.TypeOf((*MockDCGMProvider)(nil).GetEntityGroupEntities), arg0)
}

// GetGpuInstanceHierarchy mocks base method.
func (m *MockDCGMProvider) GetGpuInstanceHierarchy() (dcgm.MigHierarchy_v2, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGpuInstanceHierarchy")
	ret0, _ := ret[0].(dcgm.MigHierarchy_v2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGpuInstanceHierarchy indicates an expected call of GetGpuInstanceHierarchy.
func (mr *MockDCGMProviderMockRecorder) GetGpuInstanceHierarchy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGpuInstanceHierarchy", reflect.TypeOf((*MockDCGMProvider)(nil).GetGpuInstanceHierarchy))
}

// GetNvLinkLinkStatus mocks base method.
func (m *MockDCGMProvider) GetNvLinkLinkStatus() ([]dcgm.NvLinkStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNvLinkLinkStatus")
	ret0, _ := ret[0].([]dcgm.NvLinkStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNvLinkLinkStatus indicates an expected call of GetNvLinkLinkStatus.
func (mr *MockDCGMProviderMockRecorder) GetNvLinkLinkStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNvLinkLinkStatus", reflect.TypeOf((*MockDCGMProvider)(nil).GetNvLinkLinkStatus))
}

// GetSupportedDevices mocks base method.
func (m *MockDCGMProvider) GetSupportedDevices() ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupportedDevices")
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSupportedDevices indicates an expected call of GetSupportedDevices.
func (mr *MockDCGMProviderMockRecorder) GetSupportedDevices() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupportedDevices", reflect.TypeOf((*MockDCGMProvider)(nil).GetSupportedDevices))
}

// GetSupportedMetricGroups mocks base method.
func (m *MockDCGMProvider) GetSupportedMetricGroups(arg0 uint) ([]dcgm.MetricGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupportedMetricGroups", arg0)
	ret0, _ := ret[0].([]dcgm.MetricGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSupportedMetricGroups indicates an expected call of GetSupportedMetricGroups.
func (mr *MockDCGMProviderMockRecorder) GetSupportedMetricGroups(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupportedMetricGroups", reflect.TypeOf((*MockDCGMProvider)(nil).GetSupportedMetricGroups), arg0)
}

// GetValuesSince mocks base method.
func (m *MockDCGMProvider) GetValuesSince(arg0 dcgm.GroupHandle, arg1 dcgm.FieldHandle, arg2 time.Time) ([]dcgm.FieldValue_v2, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValuesSince", arg0, arg1, arg2)
	ret0, _ := ret[0].([]dcgm.FieldValue_v2)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetValuesSince indicates an expected call of GetValuesSince.
func (mr *MockDCGMProviderMockRecorder) GetValuesSince(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValuesSince", reflect.TypeOf((*MockDCGMProvider)(nil).GetValuesSince), arg0, arg1, arg2)
}

// GroupAllGPUs mocks base method.
func (m *MockDCGMProvider) GroupAllGPUs() dcgm.GroupHandle {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GroupAllGPUs")
	ret0, _ := ret[0].(dcgm.GroupHandle)
	return ret0
}

// GroupAllGPUs indicates an expected call of GroupAllGPUs.
func (mr *MockDCGMProviderMockRecorder) GroupAllGPUs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupAllGPUs", reflect.TypeOf((*MockDCGMProvider)(nil).GroupAllGPUs))
}

// LinkGetLatestValues mocks base method.
func (m *MockDCGMProvider) LinkGetLatestValues(arg0, arg1 uint, arg2 []dcgm.Short) ([]dcgm.FieldValue_v1, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkGetLatestValues", arg0, arg1, arg2)
	ret0, _ := ret[0].([]dcgm.FieldValue_v1)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LinkGetLatestValues indicates an expected call of LinkGetLatestValues.
func (mr *MockDCGMProviderMockRecorder) LinkGetLatestValues(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkGetLatestValues", reflect.TypeOf((*MockDCGMProvider)(nil).LinkGetLatestValues), arg0, arg1, arg2)
}

// NewDefaultGroup mocks base method.
func (m *MockDCGMProvider) NewDefaultGroup(arg0 string) (dcgm.GroupHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewDefaultGroup", arg0)
	ret0, _ := ret[0].(dcgm.GroupHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewDefaultGroup indicates an expected call of NewDefaultGroup.
func (mr *MockDCGMProviderMockRecorder) NewDefaultGroup(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewDefaultGroup", reflect.TypeOf((*MockDCGMProvider)(nil).NewDefaultGroup), arg0)
}

// UpdateAllFields mocks base method.
func (m *MockDCGMProvider) UpdateAllFields() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAllFields")
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAllFields indicates an expected call of UpdateAllFields.
func (mr *MockDCGMProviderMockRecorder) UpdateAllFields() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAllFields", reflect.TypeOf((*MockDCGMProvider)(nil).UpdateAllFields))
}

// WatchFieldsWithGroupEx mocks base method.
func (m *MockDCGMProvider) WatchFieldsWithGroupEx(arg0 dcgm.FieldHandle, arg1 dcgm.GroupHandle, arg2 int64, arg3 float64, arg4 int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WatchFieldsWithGroupEx", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// WatchFieldsWithGroupEx indicates an expected call of WatchFieldsWithGroupEx.
func (mr *MockDCGMProviderMockRecorder) WatchFieldsWithGroupEx(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchFieldsWithGroupEx", reflect.TypeOf((*MockDCGMProvider)(nil).WatchFieldsWithGroupEx), arg0, arg1, arg2, arg3, arg4)
}
