# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: What is the version?
      description: Tell us about DCGM-exporter version.
      placeholder: "example: 3.3.5-3.4.0"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Tell us what happened and provide as many details as possible, including logs.
    validations:
      required: true
  - type: textarea
    id: expectations
    attributes:
      label: What did you expect to happen?
      description: Tell us about expected behaviour.
    validations:
      required: true
  - type: textarea
    id: model
    attributes:
      label: What is the GPU model?
      description: Tell us about the hardware configuration of the GPU, including the output of 'nvidia-smi'
  - type: textarea
    id: environment
    attributes:
      label: What is the environment?
      description: Is DCGM-Exporter running on bare metal or in a virtual environment, container, pod, etc?
  - type: textarea
    id: deployment
    attributes:
      label: How did you deploy the dcgm-exporter and what is the configuration?
      description: Tell us how you deployed DCGM-Exporter. Did you use helm, build from source or use the GPU Operator?
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: How to reproduce the issue?
      description: Clear and concise steps to reproduce an issue can help everyone by allowing us to identify and fix problems more quickly.
  - type: textarea
    id: misc
    attributes:
      label: Anything else we need to know?
      description: Any small detail can help.
