// Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NVIDIA/dcgm-exporter/internal/pkg/deviceinfo (interfaces: Provider)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/pkg/deviceinfo/mock_device_info.go -package=deviceinfo -copyright_file=../../../hack/header.txt . Provider
//

// Package deviceinfo is a generated GoMock package.
package deviceinfo

import (
	reflect "reflect"

	appconfig "github.com/NVIDIA/dcgm-exporter/internal/pkg/appconfig"
	deviceinfo "github.com/NVIDIA/dcgm-exporter/internal/pkg/deviceinfo"
	dcgm "github.com/NVIDIA/go-dcgm/pkg/dcgm"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// COpts mocks base method.
func (m *MockProvider) COpts() appconfig.DeviceOptions {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "COpts")
	ret0, _ := ret[0].(appconfig.DeviceOptions)
	return ret0
}

// COpts indicates an expected call of COpts.
func (mr *MockProviderMockRecorder) COpts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "COpts", reflect.TypeOf((*MockProvider)(nil).COpts))
}

// CPU mocks base method.
func (m *MockProvider) CPU(arg0 uint) deviceinfo.CPUInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CPU", arg0)
	ret0, _ := ret[0].(deviceinfo.CPUInfo)
	return ret0
}

// CPU indicates an expected call of CPU.
func (mr *MockProviderMockRecorder) CPU(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CPU", reflect.TypeOf((*MockProvider)(nil).CPU), arg0)
}

// CPUCoreIDExists mocks base method.
func (m *MockProvider) CPUCoreIDExists(arg0 int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CPUCoreIDExists", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CPUCoreIDExists indicates an expected call of CPUCoreIDExists.
func (mr *MockProviderMockRecorder) CPUCoreIDExists(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CPUCoreIDExists", reflect.TypeOf((*MockProvider)(nil).CPUCoreIDExists), arg0)
}

// CPUIDExists mocks base method.
func (m *MockProvider) CPUIDExists(arg0 int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CPUIDExists", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CPUIDExists indicates an expected call of CPUIDExists.
func (mr *MockProviderMockRecorder) CPUIDExists(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CPUIDExists", reflect.TypeOf((*MockProvider)(nil).CPUIDExists), arg0)
}

// CPUs mocks base method.
func (m *MockProvider) CPUs() []deviceinfo.CPUInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CPUs")
	ret0, _ := ret[0].([]deviceinfo.CPUInfo)
	return ret0
}

// CPUs indicates an expected call of CPUs.
func (mr *MockProviderMockRecorder) CPUs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CPUs", reflect.TypeOf((*MockProvider)(nil).CPUs))
}

// GOpts mocks base method.
func (m *MockProvider) GOpts() appconfig.DeviceOptions {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GOpts")
	ret0, _ := ret[0].(appconfig.DeviceOptions)
	return ret0
}

// GOpts indicates an expected call of GOpts.
func (mr *MockProviderMockRecorder) GOpts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GOpts", reflect.TypeOf((*MockProvider)(nil).GOpts))
}

// GPU mocks base method.
func (m *MockProvider) GPU(arg0 uint) deviceinfo.GPUInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GPU", arg0)
	ret0, _ := ret[0].(deviceinfo.GPUInfo)
	return ret0
}

// GPU indicates an expected call of GPU.
func (mr *MockProviderMockRecorder) GPU(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GPU", reflect.TypeOf((*MockProvider)(nil).GPU), arg0)
}

// GPUCount mocks base method.
func (m *MockProvider) GPUCount() uint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GPUCount")
	ret0, _ := ret[0].(uint)
	return ret0
}

// GPUCount indicates an expected call of GPUCount.
func (mr *MockProviderMockRecorder) GPUCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GPUCount", reflect.TypeOf((*MockProvider)(nil).GPUCount))
}

// GPUIDExists mocks base method.
func (m *MockProvider) GPUIDExists(arg0 int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GPUIDExists", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GPUIDExists indicates an expected call of GPUIDExists.
func (mr *MockProviderMockRecorder) GPUIDExists(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GPUIDExists", reflect.TypeOf((*MockProvider)(nil).GPUIDExists), arg0)
}

// GPUInstanceIDExists mocks base method.
func (m *MockProvider) GPUInstanceIDExists(arg0 int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GPUInstanceIDExists", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GPUInstanceIDExists indicates an expected call of GPUInstanceIDExists.
func (mr *MockProviderMockRecorder) GPUInstanceIDExists(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GPUInstanceIDExists", reflect.TypeOf((*MockProvider)(nil).GPUInstanceIDExists), arg0)
}

// GPUs mocks base method.
func (m *MockProvider) GPUs() []deviceinfo.GPUInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GPUs")
	ret0, _ := ret[0].([]deviceinfo.GPUInfo)
	return ret0
}

// GPUs indicates an expected call of GPUs.
func (mr *MockProviderMockRecorder) GPUs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GPUs", reflect.TypeOf((*MockProvider)(nil).GPUs))
}

// InfoType mocks base method.
func (m *MockProvider) InfoType() dcgm.Field_Entity_Group {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InfoType")
	ret0, _ := ret[0].(dcgm.Field_Entity_Group)
	return ret0
}

// InfoType indicates an expected call of InfoType.
func (mr *MockProviderMockRecorder) InfoType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfoType", reflect.TypeOf((*MockProvider)(nil).InfoType))
}

// InitializeCPUInfo mocks base method.
func (m *MockProvider) InitializeCPUInfo(arg0 appconfig.DeviceOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitializeCPUInfo", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitializeCPUInfo indicates an expected call of InitializeCPUInfo.
func (mr *MockProviderMockRecorder) InitializeCPUInfo(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitializeCPUInfo", reflect.TypeOf((*MockProvider)(nil).InitializeCPUInfo), arg0)
}

// InitializeGPUInfo mocks base method.
func (m *MockProvider) InitializeGPUInfo(arg0 appconfig.DeviceOptions, arg1 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitializeGPUInfo", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitializeGPUInfo indicates an expected call of InitializeGPUInfo.
func (mr *MockProviderMockRecorder) InitializeGPUInfo(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitializeGPUInfo", reflect.TypeOf((*MockProvider)(nil).InitializeGPUInfo), arg0, arg1)
}

// InitializeNvSwitchInfo mocks base method.
func (m *MockProvider) InitializeNvSwitchInfo(arg0 appconfig.DeviceOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitializeNvSwitchInfo", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitializeNvSwitchInfo indicates an expected call of InitializeNvSwitchInfo.
func (mr *MockProviderMockRecorder) InitializeNvSwitchInfo(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitializeNvSwitchInfo", reflect.TypeOf((*MockProvider)(nil).InitializeNvSwitchInfo), arg0)
}

// IsCPUWatched mocks base method.
func (m *MockProvider) IsCPUWatched(arg0 uint) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCPUWatched", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsCPUWatched indicates an expected call of IsCPUWatched.
func (mr *MockProviderMockRecorder) IsCPUWatched(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCPUWatched", reflect.TypeOf((*MockProvider)(nil).IsCPUWatched), arg0)
}

// IsCoreWatched mocks base method.
func (m *MockProvider) IsCoreWatched(arg0, arg1 uint) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCoreWatched", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsCoreWatched indicates an expected call of IsCoreWatched.
func (mr *MockProviderMockRecorder) IsCoreWatched(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCoreWatched", reflect.TypeOf((*MockProvider)(nil).IsCoreWatched), arg0, arg1)
}

// IsLinkWatched mocks base method.
func (m *MockProvider) IsLinkWatched(arg0, arg1 uint) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLinkWatched", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsLinkWatched indicates an expected call of IsLinkWatched.
func (mr *MockProviderMockRecorder) IsLinkWatched(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLinkWatched", reflect.TypeOf((*MockProvider)(nil).IsLinkWatched), arg0, arg1)
}

// IsSwitchWatched mocks base method.
func (m *MockProvider) IsSwitchWatched(arg0 uint) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSwitchWatched", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSwitchWatched indicates an expected call of IsSwitchWatched.
func (mr *MockProviderMockRecorder) IsSwitchWatched(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSwitchWatched", reflect.TypeOf((*MockProvider)(nil).IsSwitchWatched), arg0)
}

// LinkIDExists mocks base method.
func (m *MockProvider) LinkIDExists(arg0 int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkIDExists", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// LinkIDExists indicates an expected call of LinkIDExists.
func (mr *MockProviderMockRecorder) LinkIDExists(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkIDExists", reflect.TypeOf((*MockProvider)(nil).LinkIDExists), arg0)
}

// PopulateMigProfileNames mocks base method.
func (m *MockProvider) PopulateMigProfileNames(arg0 []dcgm.GroupEntityPair) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PopulateMigProfileNames", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// PopulateMigProfileNames indicates an expected call of PopulateMigProfileNames.
func (mr *MockProviderMockRecorder) PopulateMigProfileNames(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PopulateMigProfileNames", reflect.TypeOf((*MockProvider)(nil).PopulateMigProfileNames), arg0)
}

// SOpts mocks base method.
func (m *MockProvider) SOpts() appconfig.DeviceOptions {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SOpts")
	ret0, _ := ret[0].(appconfig.DeviceOptions)
	return ret0
}

// SOpts indicates an expected call of SOpts.
func (mr *MockProviderMockRecorder) SOpts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SOpts", reflect.TypeOf((*MockProvider)(nil).SOpts))
}

// SetGPUInstanceProfileName mocks base method.
func (m *MockProvider) SetGPUInstanceProfileName(arg0 uint, arg1 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetGPUInstanceProfileName", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SetGPUInstanceProfileName indicates an expected call of SetGPUInstanceProfileName.
func (mr *MockProviderMockRecorder) SetGPUInstanceProfileName(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGPUInstanceProfileName", reflect.TypeOf((*MockProvider)(nil).SetGPUInstanceProfileName), arg0, arg1)
}

// SetMigProfileNames mocks base method.
func (m *MockProvider) SetMigProfileNames(arg0 []dcgm.FieldValue_v2) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMigProfileNames", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMigProfileNames indicates an expected call of SetMigProfileNames.
func (mr *MockProviderMockRecorder) SetMigProfileNames(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMigProfileNames", reflect.TypeOf((*MockProvider)(nil).SetMigProfileNames), arg0)
}

// Switch mocks base method.
func (m *MockProvider) Switch(arg0 uint) deviceinfo.SwitchInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Switch", arg0)
	ret0, _ := ret[0].(deviceinfo.SwitchInfo)
	return ret0
}

// Switch indicates an expected call of Switch.
func (mr *MockProviderMockRecorder) Switch(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Switch", reflect.TypeOf((*MockProvider)(nil).Switch), arg0)
}

// SwitchIDExists mocks base method.
func (m *MockProvider) SwitchIDExists(arg0 int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SwitchIDExists", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SwitchIDExists indicates an expected call of SwitchIDExists.
func (mr *MockProviderMockRecorder) SwitchIDExists(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchIDExists", reflect.TypeOf((*MockProvider)(nil).SwitchIDExists), arg0)
}

// Switches mocks base method.
func (m *MockProvider) Switches() []deviceinfo.SwitchInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Switches")
	ret0, _ := ret[0].([]deviceinfo.SwitchInfo)
	return ret0
}

// Switches indicates an expected call of Switches.
func (mr *MockProviderMockRecorder) Switches() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Switches", reflect.TypeOf((*MockProvider)(nil).Switches))
}

// VerifyCPUDevicePresence mocks base method.
func (m *MockProvider) VerifyCPUDevicePresence(arg0 appconfig.DeviceOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyCPUDevicePresence", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyCPUDevicePresence indicates an expected call of VerifyCPUDevicePresence.
func (mr *MockProviderMockRecorder) VerifyCPUDevicePresence(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyCPUDevicePresence", reflect.TypeOf((*MockProvider)(nil).VerifyCPUDevicePresence), arg0)
}

// VerifyDevicePresence mocks base method.
func (m *MockProvider) VerifyDevicePresence(arg0 appconfig.DeviceOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyDevicePresence", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyDevicePresence indicates an expected call of VerifyDevicePresence.
func (mr *MockProviderMockRecorder) VerifyDevicePresence(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyDevicePresence", reflect.TypeOf((*MockProvider)(nil).VerifyDevicePresence), arg0)
}

// VerifySwitchDevicePresence mocks base method.
func (m *MockProvider) VerifySwitchDevicePresence(arg0 appconfig.DeviceOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifySwitchDevicePresence", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifySwitchDevicePresence indicates an expected call of VerifySwitchDevicePresence.
func (mr *MockProviderMockRecorder) VerifySwitchDevicePresence(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifySwitchDevicePresence", reflect.TypeOf((*MockProvider)(nil).VerifySwitchDevicePresence), arg0)
}
