//go:build e2e

/*
 * Copyright (c) 2026, NVIDIA CORPORATION.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package k8s

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"strings"
	"time"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	corev1 "k8s.io/api/core/v1"
)

var _ = Describe("dcgm-exporter configuration scenarios", func() {
	Context("DCGM exporter is deployed on kubernetes and TLS is enabled", Ordered, Label("tls"), func() {
		var dcgmExpPod *corev1.Pod

		AfterAll(func(ctx context.Context) {
			cleanupTestContext(ctx, kubeClient, helmClient)
		})

		It("should install dcgm-exporter helm chart [tls]", func(ctx context.Context) {
			shouldInstallHelmChart(ctx, helmClient, []string{
				"tlsServerConfig.enabled=true",
				"tlsServerConfig.autoGenerated=true",
			})
		})

		It("should create dcgm-exporter pod [tls]", func(ctx context.Context) {
			dcgmExpPod = shouldCheckIfPodCreated(ctx, kubeClient, dcgmExporterPodLabels)
		})

		It("should ensure that the dcgm-exporter pod is ready [tls]", func(ctx context.Context) {
			shouldCheckIfPodIsReady(ctx, kubeClient, dcgmExpPod.Namespace, dcgmExpPod.Name)
		})

		It("should check that the port accepts TLS [tls]", func(ctx context.Context) {
			status, body := shouldHTTPRequestPodPort(ctx, dcgmExpPod, false, "", "")
			Expect(status).To(Equal(http.StatusBadRequest))
			Expect(string(body)).To(ContainSubstring("Client sent an HTTP request to an HTTPS server"))

			status, body = shouldHTTPRequestPodPort(ctx, dcgmExpPod, true, "", "")
			Expect(status).To(Equal(http.StatusOK))
			shouldVerifyBaselineMetricContract(body, false)
		})
	})

	Context("DCGM exporter is deployed on kubernetes and HTTP basic auth is enabled", Ordered, Label("basicAuth"), func() {
		var dcgmExpPod *corev1.Pod

		AfterAll(func(ctx context.Context) {
			cleanupTestContext(ctx, kubeClient, helmClient)
		})

		It("should install dcgm-exporter helm chart [basicAuth]", func(ctx context.Context) {
			shouldInstallHelmChart(ctx, helmClient, []string{
				"basicAuth.users.admin=admin",
			})
		})

		It("should create dcgm-exporter pod [basicAuth]", func(ctx context.Context) {
			dcgmExpPod = shouldCheckIfPodCreated(ctx, kubeClient, dcgmExporterPodLabels)
		})

		It("should ensure that the dcgm-exporter pod is ready [basicAuth]", func(ctx context.Context) {
			shouldCheckIfPodIsReady(ctx, kubeClient, dcgmExpPod.Namespace, dcgmExpPod.Name)
		})

		It("should check that the metric endpoint protected by basic HTTP auth [basicAuth]", func(ctx context.Context) {
			status, body := shouldHTTPRequestPodPort(ctx, dcgmExpPod, false, "", "")
			Expect(status).To(Equal(http.StatusUnauthorized))
			Expect(string(body)).To(ContainSubstring("Unauthorized"))

			status, body = shouldHTTPRequestPodPort(ctx, dcgmExpPod, false, "admin", "admin")
			Expect(status).To(Equal(http.StatusOK))
			shouldVerifyBaselineMetricContract(body, false)
		})
	})

	Context("DCGM exporter exposes TLS and basic auth together", Ordered, Label("tlsBasicAuth"), func() {
		var dcgmExpPod *corev1.Pod

		AfterAll(func(ctx context.Context) {
			cleanupTestContext(ctx, kubeClient, helmClient)
		})

		It("should deploy with TLS and basic auth enabled", func(ctx context.Context) {
			shouldInstallHelmChart(ctx, helmClient, []string{
				"tlsServerConfig.enabled=true",
				"tlsServerConfig.autoGenerated=true",
				"basicAuth.users.admin=admin",
			})
			dcgmExpPod = shouldCheckIfPodCreated(ctx, kubeClient, dcgmExporterPodLabels)
			shouldCheckIfPodIsReady(ctx, kubeClient, dcgmExpPod.Namespace, dcgmExpPod.Name)
		})

		It("should require basic auth over HTTPS and emit valid metrics", func(ctx context.Context) {
			status, body := shouldHTTPRequestPodPort(ctx, dcgmExpPod, true, "", "")
			Expect(status).To(Equal(http.StatusUnauthorized))
			Expect(string(body)).To(ContainSubstring("Unauthorized"))

			status, body = shouldHTTPRequestPodPort(ctx, dcgmExpPod, true, "admin", "admin")
			Expect(status).To(Equal(http.StatusOK))
			Expect(baselineMetricContractError(body, false)).To(Succeed())
		})
	})

	Context("DCGM exporter suppresses hostname labels", Ordered, Label("noHostname"), func() {
		AfterAll(func(ctx context.Context) {
			cleanupTestContext(ctx, kubeClient, helmClient)
		})

		It("should omit hostname labels while retaining GPU metrics", func(ctx context.Context) {
			_, _ = shouldInstallExporterAndReadMetrics(ctx,
				[]string{exporterArguments("--no-hostname")},
				nil,
				testRunLabels,
				noHostnameMetricContractError)
		})
	})

	Context("DCGM exporter normalizes model names", Ordered, Label("modelName"), func() {
		AfterAll(func(ctx context.Context) {
			cleanupTestContext(ctx, kubeClient, helmClient)
		})

		It("should replace blanks in modelName label values", func(ctx context.Context) {
			_, _ = shouldInstallExporterAndReadMetrics(ctx,
				[]string{exporterArguments("--replace-blanks-in-model-name")},
				nil,
				testRunLabels,
				func(metrics []byte) error {
					return errors.Join(
						baselineMetricContractError(metrics, true),
						metricLabelValuesDoNotContain(metrics, "modelName", " "),
					)
				})
		})
	})

	Context("DCGM exporter pprof endpoint is controlled by configuration", Ordered, Label("pprof"), func() {
		var (
			dcgmExpPod      *corev1.Pod
			helmReleaseName string
		)

		AfterAll(func(ctx context.Context) {
			cleanupTestContext(ctx, kubeClient, helmClient)
		})

		It("should hide pprof by default and expose it when enabled", func(ctx context.Context) {
			helmReleaseName = shouldInstallHelmChart(ctx, helmClient, nil)
			dcgmExpPod = shouldCheckIfPodCreated(ctx, kubeClient, dcgmExporterPodLabels)
			shouldCheckIfPodIsReady(ctx, kubeClient, dcgmExpPod.Namespace, dcgmExpPod.Name)

			status, _ := shouldHTTPRequestPodPortPath(ctx, dcgmExpPod, false, "", "", "debug/pprof/")
			Expect(status).To(Equal(http.StatusNotFound))

			shouldUpgradeHelmChart(ctx, helmClient, helmReleaseName, []string{
				exporterArguments("--enable-pprof"),
				"basicAuth.users.admin=admin",
			}, nil)
			Expect(kubeClient.DeletePod(ctx, dcgmExpPod.Namespace, dcgmExpPod.Name)).To(Succeed())
			dcgmExpPod = shouldCheckIfReplacementPodCreated(ctx, kubeClient, dcgmExporterPodLabels, dcgmExpPod)
			shouldCheckIfPodIsReady(ctx, kubeClient, dcgmExpPod.Namespace, dcgmExpPod.Name)

			status, _ = shouldHTTPRequestPodPortPath(ctx, dcgmExpPod, false, "", "", "debug/pprof/")
			Expect(status).To(Equal(http.StatusUnauthorized))

			status, body := shouldHTTPRequestPodPortPath(ctx, dcgmExpPod, false, "admin", "admin", "debug/pprof/")
			Expect(status).To(Equal(http.StatusOK))
			Expect(string(body)).To(ContainSubstring("pprof"))
		})
	})

	Context("DCGM exporter writes debug dump files", Ordered, Label("debugDump"), func() {
		AfterAll(func(ctx context.Context) {
			cleanupTestContext(ctx, kubeClient, helmClient)
		})

		It("should write metrics and device info dumps after scraping", func(ctx context.Context) {
			_, _ = shouldInstallExporterAndReadMetrics(ctx,
				[]string{
					"debugDump.enabled=true",
					fmt.Sprintf("debugDump.directory=%s", debugDumpDirectory),
					"debugDump.retention=0",
					"debugDump.compression=false",
				},
				nil,
				testRunLabels,
				func(metrics []byte) error {
					return baselineMetricContractError(metrics, true)
				})

			readerPod := shouldCreateDebugDumpReaderPod(ctx)
			Eventually(func(g Gomega) {
				stdout, stderr, err := kubeClient.ExecutePodCommand(ctx,
					readerPod.Namespace,
					readerPod.Name,
					"reader",
					[]string{"sh", "-c", "find /debug-dumps -type f | wc -l"},
				)
				g.Expect(err).NotTo(HaveOccurred(), stderr)
				g.Expect(strings.TrimSpace(stdout)).NotTo(Equal("0"))
			}).WithPolling(2 * time.Second).Within(1 * time.Minute).Should(Succeed())
		})
	})

	Context("DCGM exporter applies HPC job mapping labels", Ordered, Label("hpcJobMapping"), func() {
		AfterAll(func(ctx context.Context) {
			cleanupTestContext(ctx, kubeClient, helmClient)
		})

		It("should emit hpc_job labels from mounted GPU job files", func(ctx context.Context) {
			shouldCreateHPCJobMappingConfigMap(ctx)
			_, _ = shouldInstallExporterAndReadMetrics(ctx,
				[]string{
					exporterArguments(fmt.Sprintf("--hpc-job-mapping-dir=%s", hpcJobMappingDir)),
				},
				hpcJobMappingJSONValues(),
				testRunLabels,
				func(metrics []byte) error {
					return errors.Join(
						baselineMetricContractError(metrics, true),
						metricsHaveLabelValue(metrics, "hpc_job", hpcJobName),
					)
				})
		})
	})

	Context("DCGM exporter honors configured NVIDIA resource names", Ordered, Label("customResourceNames"), func() {
		AfterAll(func(ctx context.Context) {
			cleanupTestContext(ctx, kubeClient, helmClient)
		})

		It("should keep workload attribution valid when resource names are configured", func(ctx context.Context) {
			_, _ = shouldInstallExporterAndReadMetrics(ctx,
				[]string{
					"extraEnv[0].name=NVIDIA_RESOURCE_NAMES",
					"extraEnv[0].value=nvidia.com/gpu",
				},
				nil,
				testRunLabels,
				func(metrics []byte) error {
					return baselineMetricContractError(metrics, true)
				})
		})
	})
})
