// Copyright (c) 2026, NVIDIA CORPORATION.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestParseTargets(t *testing.T) {
	t.Parallel()

	targets, err := parseTargets("linux/arm64, linux/amd64,linux/arm64")
	if err != nil {
		t.Fatalf("parse targets: %v", err)
	}

	got := targetNames(targets)
	want := []string{"linux/amd64", "linux/arm64"}
	if len(got) != len(want) {
		t.Fatalf("target count = %d, want %d", len(got), len(want))
	}
	for index := range want {
		if got[index] != want[index] {
			t.Errorf("target %d = %q, want %q", index, got[index], want[index])
		}
	}
}

func TestParseTargetsRejectsInvalidValue(t *testing.T) {
	t.Parallel()

	if _, err := parseTargets("linux"); err == nil {
		t.Fatal("parseTargets accepted a target without an architecture")
	}
}

func TestIsLegalFileName(t *testing.T) {
	t.Parallel()

	for _, test := range []struct {
		name string
		want bool
	}{
		{name: "LICENSE", want: true},
		{name: "LICENCE.md", want: true},
		{name: "LICENSE-APACHE", want: true},
		{name: "NOTICE.txt", want: true},
		{name: "COPYING", want: true},
		{name: "README.md", want: false},
		{name: "licenses.md", want: false},
	} {
		test := test
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			if got := isLegalFileName(test.name); got != test.want {
				t.Errorf("isLegalFileName(%q) = %t, want %t", test.name, got, test.want)
			}
		})
	}
}

func TestReadNoticeFilesUsesSortedTopLevelLegalFiles(t *testing.T) {
	t.Parallel()

	directory := t.TempDir()
	for name, contents := range map[string]string{
		"LICENSE-Z": "license z",
		"NOTICE":    "notice",
		"README.md": "not legal material",
	} {
		if err := os.WriteFile(filepath.Join(directory, name), []byte(contents), 0o600); err != nil {
			t.Fatalf("write %s: %v", name, err)
		}
	}

	files, err := readNoticeFiles(directory)
	if err != nil {
		t.Fatalf("read notice files: %v", err)
	}
	if got, want := len(files), 2; got != want {
		t.Fatalf("notice file count = %d, want %d", got, want)
	}
	if got, want := files[0].Name, "LICENSE-Z"; got != want {
		t.Errorf("first notice file = %q, want %q", got, want)
	}
	if got, want := files[1].Name, "NOTICE"; got != want {
		t.Errorf("second notice file = %q, want %q", got, want)
	}
}

func TestReadNoticeFilesRejectsBlankLegalFile(t *testing.T) {
	t.Parallel()

	directory := t.TempDir()
	if err := os.WriteFile(filepath.Join(directory, "LICENSE"), []byte(" \t\r\n\n"), 0o600); err != nil {
		t.Fatalf("write blank legal file: %v", err)
	}

	_, err := readNoticeFiles(directory)
	if err == nil || !strings.Contains(err.Error(), "LICENSE is empty") {
		t.Fatalf("read notice files error = %v, want blank-file failure", err)
	}
}

func TestRenderNoticesContract(t *testing.T) {
	t.Parallel()

	got := string(renderNotices(
		"./cmd/example",
		[]target{{GOOS: "linux", GOARCH: "amd64"}, {GOOS: "linux", GOARCH: "arm64"}},
		[]component{{
			Path:    "example.com/dependency",
			Version: "v1.2.3",
			NoticeFiles: []noticeFile{
				{Name: "LICENSE", Text: []byte("license text\n")},
				{Name: "NOTICE", Text: []byte("notice text")},
			},
		}},
	))
	want := `THIRD-PARTY NOTICES FOR THE DCGM-EXPORTER BINARY

This generated file contains the legal materials supplied by third-party Go modules compiled into the production dcgm-exporter binary for the targets below.
It is intended to ship beside the project LICENSE in standalone binary distributions.
Runtime libraries supplied by the host are not part of that binary payload and are outside this file's scope.
Container images combine this file with the legal materials for every additional component they ship. Do not edit this file manually.
Package: ./cmd/example
Targets: linux/amd64, linux/arm64
Scope: third-party Go code compiled into the production dcgm-exporter binary.
NVIDIA-authored modules are excluded from this third-party notice bundle.
Excluded: dynamically supplied host libraries and other files not contained in the standalone binary payload.

================================================================================
Module: example.com/dependency
Version: v1.2.3
File: LICENSE
File: NOTICE
================================================================================

--- LICENSE ---

license text

--- NOTICE ---

notice text
`
	if got != want {
		t.Errorf("rendered notices mismatch\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestReadNoticeFilesPreservesExactLegalBytes(t *testing.T) {
	t.Parallel()

	directory := t.TempDir()
	want := []byte("first line  \r\nsecond line\n\n")
	if err := os.WriteFile(filepath.Join(directory, "LICENSE"), want, 0o600); err != nil {
		t.Fatalf("write license: %v", err)
	}
	files, err := readNoticeFiles(directory)
	if err != nil {
		t.Fatalf("read notice files: %v", err)
	}
	if got := files[0].Text; string(got) != string(want) {
		t.Errorf("legal bytes = %q, want %q", got, want)
	}
}

func TestListModulesDisablesWorkspaceOverrides(t *testing.T) {
	moduleDirectory := t.TempDir()
	commandLog := configureFakeGo(t, moduleDirectory)
	t.Setenv("GOWORK", filepath.Join(t.TempDir(), "injected.go.work"))

	modules, err := listModules("./cmd/dcgm-exporter", target{GOOS: "linux", GOARCH: "amd64"})
	if err != nil {
		t.Fatalf("list modules: %v", err)
	}
	if got, want := len(modules), 1; got != want {
		t.Fatalf("module count = %d, want %d", got, want)
	}
	if got, want := modules[0].key(), "example.com/dependency@v1.0.0"; got != want {
		t.Errorf("module key = %q, want %q", got, want)
	}

	assertCommandLog(t, commandLog, "list -buildvcs=false -deps -json ./cmd/dcgm-exporter\n")
}

func TestCollectComponentsVerifiesModuleCacheBeforeReadingNotices(t *testing.T) {
	moduleDirectory := t.TempDir()
	commandLog := configureFakeGo(t, moduleDirectory)
	t.Setenv("FAKE_GO_LICENSE_PATH", filepath.Join(moduleDirectory, "LICENSE"))

	components, err := collectComponents("./cmd/dcgm-exporter", []target{{GOOS: "linux", GOARCH: "amd64"}})
	if err != nil {
		t.Fatalf("collect components: %v", err)
	}
	if got, want := len(components), 1; got != want {
		t.Fatalf("component count = %d, want %d", got, want)
	}
	if got, want := components[0].NoticeFiles[0].Name, "LICENSE"; got != want {
		t.Errorf("notice file = %q, want %q", got, want)
	}

	assertCommandLog(t, commandLog, "list -buildvcs=false -deps -json ./cmd/dcgm-exporter\nmod verify\n")
}

func TestCollectComponentsExcludesNVIDIAFirstPartyModules(t *testing.T) {
	moduleDirectory := t.TempDir()
	configureFakeGo(t, moduleDirectory)
	t.Setenv("FAKE_GO_LICENSE_PATH", filepath.Join(moduleDirectory, "LICENSE"))
	listOutput := filepath.Join(t.TempDir(), "list.json")
	t.Setenv("FAKE_GO_LIST_OUTPUT", listOutput)
	metadata := fmt.Sprintf(
		"{\"Module\":{\"Path\":\"github.com/NVIDIA/go-dcgm\",\"Version\":\"v1.0.0\",\"Dir\":%q}}\n"+
			"{\"Module\":{\"Path\":\"github.com/NVIDIA/go-nvml\",\"Version\":\"v1.0.0\",\"Dir\":%q}}\n"+
			"{\"Module\":{\"Path\":\"example.com/dependency\",\"Version\":\"v1.0.0\",\"Dir\":%q}}\n",
		filepath.Join(t.TempDir(), "go-dcgm"), filepath.Join(t.TempDir(), "go-nvml"), moduleDirectory)
	if err := os.WriteFile(listOutput, []byte(metadata), 0o600); err != nil {
		t.Fatalf("write fake module list: %v", err)
	}

	components, err := collectComponents("./cmd/dcgm-exporter", []target{{GOOS: "linux", GOARCH: "amd64"}})
	if err != nil {
		t.Fatalf("collect components: %v", err)
	}
	if got, want := len(components), 1; got != want {
		t.Fatalf("component count = %d, want %d", got, want)
	}
	if got, want := components[0].Path, "example.com/dependency"; got != want {
		t.Errorf("component path = %q, want %q", got, want)
	}
}

func TestCollectComponentsStopsOnModuleVerificationFailure(t *testing.T) {
	moduleDirectory := t.TempDir()
	commandLog := configureFakeGo(t, moduleDirectory)
	t.Setenv("FAKE_GO_VERIFY_ERROR", "example.com/dependency@v1.0.0: checksum mismatch")

	_, err := collectComponents("./cmd/dcgm-exporter", []target{{GOOS: "linux", GOARCH: "amd64"}})
	if err == nil {
		t.Fatal("collectComponents accepted a module-cache verification failure")
	}
	if !strings.Contains(err.Error(), "verify module cache") || !strings.Contains(err.Error(), "checksum mismatch") {
		t.Fatalf("verification error = %q, want command context and command output", err)
	}

	assertCommandLog(t, commandLog, "list -buildvcs=false -deps -json ./cmd/dcgm-exporter\nmod verify\n")
}

func configureFakeGo(t *testing.T, moduleDirectory string) string {
	t.Helper()

	binDirectory := t.TempDir()
	goPath := filepath.Join(binDirectory, "go")
	program := `#!/bin/sh
set -eu
printf '%s\n' "$*" >> "${FAKE_GO_LOG}"
if [ "${GOWORK:-}" != "off" ]; then
	printf 'unexpected GOWORK=%s\n' "${GOWORK:-}" >&2
	exit 40
fi
if [ "$1" = "list" ]; then
	cat "${FAKE_GO_LIST_OUTPUT}"
	exit 0
fi
if [ "$1" = "mod" ] && [ "$2" = "verify" ]; then
	if [ -n "${FAKE_GO_VERIFY_ERROR:-}" ]; then
		printf '%s\n' "${FAKE_GO_VERIFY_ERROR}" >&2
		exit 41
	fi
	if [ -n "${FAKE_GO_LICENSE_PATH:-}" ]; then
		printf 'test license\n' > "${FAKE_GO_LICENSE_PATH}"
	fi
	printf 'all modules verified\n'
	exit 0
fi
printf 'unexpected go command: %s\n' "$*" >&2
exit 42
`
	// #nosec G306 -- the private test helper must be executable.
	if err := os.WriteFile(goPath, []byte(program), 0o700); err != nil {
		t.Fatalf("write fake go executable: %v", err)
	}

	listOutput := filepath.Join(t.TempDir(), "list.json")
	metadata := fmt.Sprintf("{\"Module\":{\"Path\":\"example.com/dependency\",\"Version\":\"v1.0.0\",\"Dir\":%q}}\n", moduleDirectory)
	if err := os.WriteFile(listOutput, []byte(metadata), 0o600); err != nil {
		t.Fatalf("write fake go list output: %v", err)
	}

	commandLog := filepath.Join(t.TempDir(), "commands.log")
	t.Setenv("PATH", binDirectory+string(os.PathListSeparator)+os.Getenv("PATH"))
	t.Setenv("FAKE_GO_LOG", commandLog)
	t.Setenv("FAKE_GO_LIST_OUTPUT", listOutput)
	return commandLog
}

func assertCommandLog(t *testing.T, path, want string) {
	t.Helper()

	contents, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read fake go command log: %v", err)
	}
	if got := string(contents); got != want {
		t.Errorf("go command log = %q, want %q", got, want)
	}
}
